# Generated by Django 4.1.3 on 2024-02-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbuddyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
