# Generated by Django 4.1.3 on 2024-02-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbuddyapi', '0003_brew_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brew',
            name='completed',
        ),
        migrations.AddField(
            model_name='brew',
            name='stage',
            field=models.CharField(default='Not Started', max_length=50),
        ),
    ]
