# Generated by Django 4.1.3 on 2024-02-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbuddyapi', '0004_remove_brew_completed_brew_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='image',
            field=models.URLField(default='https://myfermentedfoods.com/wp-content/uploads/2019/11/Mead.jpg'),
        ),
    ]
